[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = "0.3"
yew-router = "0.18.0"

[lib]
crate-type = ["cdylib"]