[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
no_autoreload = true

[[hooks]]
stage = "post_build"
command = "cmd"
command_arguments = ["/C", "xcopy /E /I /Y static dist\\static"]

[clean]
dist = "dist"
cargo = false
