[package]
name = "oxidizedoasis-websands"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3"
actix-files = "0.6"
actix-cors = "0.6"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "uuid"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
bcrypt = "0.13"
uuid = { version = "1.3", features = ["v4", "serde"] }