[package]
name = "test_common"
version = "0.1.0"
edition = "2021"

[dependencies]
oxidizedoasis-websands = { path = "../../" }
sqlx = { version = "=0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono", "uuid", "json"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.17", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
bcrypt = "0.17.0"
jsonwebtoken = "9.3"
serde_json = "1.0.142"
actix-web = { version = "=4.11.0" }
mockall = "^0.13.1"
serde = { version = "1.0", features = ["derive"] }
